services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: run_sous_bpm_db
    environment:
      POSTGRES_USER: run_sous_bpm
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: run_sous_bpm
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U run_sous_bpm -d run_sous_bpm"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  timescaledb_data:
