//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "track")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub artist_name: String,
    #[sea_orm(column_type = "Text")]
    pub track_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub album_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub artist_mbid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub track_mbid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub album_mbid: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lastfm_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::listen::Entity")]
    Listen,
}

impl Related<super::listen::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Listen.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
